--- wikilinks.lua — resolve [[bare-slug]] links for the published site.
--
-- The corpus is authored with Obsidian-style bare-slug wikilinks so it stays
-- readable on GitHub and in a markdown editor. Quarto does not understand them,
-- so this filter rewrites each [[slug]] into a real link using a slug -> path
-- map generated by scripts/build-slugmap.R and injected via metadata-files.
--
-- Slugs are unique wiki-wide (enforced by scripts/check-links.sh), so a bare
-- slug is sufficient to resolve. An unresolved slug renders as visible marked-up
-- text rather than silently vanishing.

local slugmap = {}
local titlemap = {}
local depth = 0          -- directory depth of the file being rendered

local function get_meta(meta)
  if meta.wikislugs then
    for slug, entry in pairs(meta.wikislugs) do
      if type(entry) == 'table' and entry.path then
        slugmap[slug] = pandoc.utils.stringify(entry.path)
        if entry.title then
          titlemap[slug] = pandoc.utils.stringify(entry.title)
        end
      else
        slugmap[slug] = pandoc.utils.stringify(entry)
      end
    end
  end

  -- Work out how far the current document sits below the project root so the
  -- generated hrefs can be made relative to it.
  --
  -- PANDOC_STATE.input_files is NOT usable here: Quarto renders through a temp
  -- file, so it reports something like /var/folders/.../quarto-input<hash>.md
  -- and counting its separators yields a nonsense depth. quarto.doc.input_file
  -- is the real source path.
  local src = nil
  if quarto and quarto.doc and quarto.doc.input_file then
    src = quarto.doc.input_file
  end

  depth = 0
  if src then
    local root = os.getenv('QUARTO_PROJECT_DIR')
    local rel = src
    if root and #root > 0 then
      root = root:gsub('/+$', '')
      if src:sub(1, #root + 1) == root .. '/' then
        rel = src:sub(#root + 2)
      end
    end
    -- Fall back to cutting at a known top-level corpus directory.
    if rel:sub(1, 1) == '/' then
      local cut = rel:find('/wiki/') or rel:find('/documents/')
      if cut then rel = rel:sub(cut + 1) end
    end
    for _ in rel:gmatch('/') do depth = depth + 1 end
  end
end

local function relative(path)
  if depth == 0 then return path end
  return string.rep('../', depth) .. path
end

--- Replace every [[slug]] occurrence inside a run of inlines.
local function expand(inlines)
  local out = pandoc.List()
  local i = 1
  local changed = false

  while i <= #inlines do
    local el = inlines[i]

    -- Pandoc parses [[slug]] as Str "[[slug]]" when the slug has no spaces or
    -- punctuation that would split it, but a hyphenated slug survives as one
    -- Str, which is the case the corpus uses throughout.
    if el.t == 'Str' and el.text:find('%[%[') then
      local text = el.text
      local pos = 1
      while true do
        local s, e, slug = text:find('%[%[([^%]]+)%]%]', pos)
        if not s then break end
        changed = true
        if s > pos then
          out:insert(pandoc.Str(text:sub(pos, s - 1)))
        end

        local target = slugmap[slug]
        local label = titlemap[slug] or slug
        if target then
          out:insert(pandoc.Link(pandoc.Str(label), relative(target)))
        else
          -- Unresolved: keep it visible so it gets noticed and fixed.
          out:insert(pandoc.Span(pandoc.Str(slug), {class = 'wikilink-unresolved'}))
          io.stderr:write('wikilinks.lua: unresolved [[' .. slug .. ']]\n')
        end
        pos = e + 1
      end
      if changed and pos <= #text then
        out:insert(pandoc.Str(text:sub(pos)))
      elseif not changed then
        out:insert(el)
      end
    else
      out:insert(el)
    end
    i = i + 1
  end

  if changed then return out end
  return nil
end

return {
  { Meta = get_meta },
  { Inlines = expand },
}
